### ISSUE TITLE
Demo of code snippet for web embedding does not appear

### ISSUE THREAD

**Issue by HughCraig** [HughCraig/TLCMap#112]
I get a 'tlcmap.org refused to connect' error message when I go to 'Share' from a multilayer map, e.g. https://www.tlcmap.org/view/collection-3d.html?load=https://www.tlcmap.org/ghap/publiccollections/4/json

**Comment by BillPascoe** [comment]
This appears to be due to CORS issues. The error message in the Console is:
Refused to display 'https://tlcmap.org/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
A year or so ago Google added extra constraints to make it harder to embed and share content across websites. This was for security, and because people usually want to protect their IP, but it makes it hard for free information and open data folks like us. It's still possible but you have to put in a lot of extra config etc to allow it to work, we must have missed those bits in the upgrade. I'm looking into it.

**Comment by BillPascoe** [comment]
needed .htaccess file in the /view folder with this:
Header always unset X-Frame-Options

**Comment by BillPascoe** [comment]
Yang, please add .htaccess file to view folder in the repo for next time.

**Comment by yangli0516** [comment]
Added .htaccess file, also with the content to disable directory listing. At some stage we will probably remove the index.php from the 'view' directory.
